version: '3.7'
services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8050:8050"
      - "8051:8051"
    volumes:
      - ./api/auth/:/var/www/auth
      - ./api/fmanager/:/var/www/fmanager
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/web/:/etc/nginx/conf.d/
    networks:
      - s_net

  db:
    image: mysql:8.0
    restart: unless-stopped
    tty: true
    ports:
      - "33091:3306"
    environment:
      MYSQL_DATABASE: base
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - ./docker/mysql/dbdata:/var/lib/mysql
      - /home/mysql/mysql-files:/var/lib/mysql-files/
    networks:
      - s_net

  auth:
    build:
      context: api/auth
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: auth
      SERVICE_TAGS: dev
    working_dir: /var/www/auth
    volumes:
      - ./api/auth/:/var/www/auth
    networks:
      - s_net

  fmanager:
    build:
      context: api/fmanager
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: fmanager
      SERVICE_TAGS: dev
    working_dir: /var/www/fmanager
    volumes:
      - ./api/fmanager/:/var/www/fmanager
    networks:
      - s_net

networks:
  s_net:
    driver: bridge
    ipam:
      config:
        - subnet: "173.18.0.1/24"